export const offers = [
  {
    id: "abcd1234cdbw",
    imgUrl: "https://links.papareact.com/gn7",
    title: "Special Sushi",
    rating: "5",
    genre: "continental",
    genreId: "y777yyrfdd12345",
    address: "wall street,cole road",
    short_description: "healthy meal,for all",
    dishes: [],
    long: 45,
    lat: 5,
  },
  {
    id: "efgh1234cebl",
    imgUrl: "https://www.nandos.com/wp-content/uploads/2022/04/our-food.jpg",
    title: "Nando's",
    rating: "4.5",
    genre: "fast food",
    genreId: "y777yyrfdd1234",
    address: "welsh street,cool drive",
    short_description: "enjoyable fast meal",
    dishes: [],
    long: 45,
    lat: 5,
  },

  {
    id: "efghrr556777ieb0",
    imgUrl:
      "https://media-cdn.tripadvisor.com/media/photo-s/15/9e/05/d1/grilled-prawn.jpg",
    title: "Turtle Bay",
    rating: "4.9",
    genre: "sea food",
    genreId: "y777yyrfdd123456",
    address: "wall street,cole road",
    short_description: "sea food delight",
    dishes: [],
    long: 45,
    lat: 5,
  },
  {
    id: "yytuivvvgyy78",
    imgUrl:
      "https://hips.hearstapps.com/hmg-prod/images/cold-stone-creamery-halloween-boo-batter-ice-cream-1601567052.jpg",
    title: "Cold Stone Creamery",
    rating: "3.5",
    genre: "ice cream",
    genreId: "y777yyrfdd1234567",
    address: "stone street,cold avenue",
    short_description: "yummy flavours available",
    dishes: [],
    long: 45,
    lat: 5,
  },
  {
    id: "667gttyu6777",
    imgUrl:
      "https://d1ralsognjng37.cloudfront.net/018f79b0-182e-4c4f-a625-8600e582a1e1.jpeg",
    title: "KFC",
    rating: "4.0",
    genre: "fast food",
    genreId: "y777yyrfdd1234",
    address: "Aron's ville,Duncan drive",
    short_description: "Delicious Crispy Chickens",
    dishes: [],
    long: 45,
    lat: 5,
  },
  {
    id: "aadyu887tgghjuyu",
    imgUrl:
      "https://media-cdn.tripadvisor.com/media/photo-s/1d/45/34/3a/wide-range-of-international.jpg",
    title: "De Bull Restaurant and Bar",
    rating: "4.6",
    genre: "fine dining",
    genreId: "y777yyrfdd12345678",
    address: "BBQ road, A Avenue",
    short_description: "Enjoy meals like never before",
    dishes: [],
    long: 45,
    lat: 5,
  },
  {
    id: "6hy665gr4433rf5",
    imgUrl:
      "https://res.cloudinary.com/hello-world/image/upload/v1551791304/gn1q5yxi4urkp2dohjfu.jpg",
    title: "Ocean Basket",
    rating: "4.3",
    genre: "fine dining",
    genreId: "y777yyrfdd12345678",
    address: "wall street,cole road",
    short_description: "Enjoy sea food with comfort",
    dishes: [],
    long: 45,
    lat: 5,
  },
];
export const discount = [
  {
    id: "efgh1234cebl",
    imgUrl: "https://www.nandos.com/wp-content/uploads/2022/04/our-food.jpg",
    title: "Nando's",
    rating: "4.5",
    genre: "fast food",
    genreId: "y777yyrfdd1234",
    address: "welsh street,cool drive",
    short_description: "enjoyable fast meal",
    dishes: [],
    long: 45,
    lat: 5,
  },

  {
    id: "efghrr556777ieb0",
    imgUrl:
      "https://media-cdn.tripadvisor.com/media/photo-s/15/9e/05/d1/grilled-prawn.jpg",
    title: "Turtle Bay",
    rating: "4.9",
    genre: "sea food",
    genreId: "y777yyrfdd123456",
    address: "wall street,cole road",
    short_description: "sea food delight",
    dishes: [],
    long: 45,
    lat: 5,
  },
  {
    id: "yytuivvvgyy78",
    imgUrl:
      "https://hips.hearstapps.com/hmg-prod/images/cold-stone-creamery-halloween-boo-batter-ice-cream-1601567052.jpg",
    title: "Cold Stone Creamery",
    rating: "3.5",
    genre: "fast food",
    genreId: "y777yyrfdd1234",
    address: "stone street,cold avenue",
    short_description: "yummy flavours available",
    dishes: [],
    long: 45,
    lat: 5,
  },
  {
    id: "667gttyu6777",
    imgUrl:
      "https://d1ralsognjng37.cloudfront.net/018f79b0-182e-4c4f-a625-8600e582a1e1.jpeg",
    title: "KFC",
    rating: "4.0",
    genre: "fast food",
    genreId: "y777yyrfdd1234",
    address: "Aron's ville,Duncan drive",
    short_description: "Delicious Crispy Chickens",
    dishes: [],
    long: 45,
    lat: 5,
  },
];

export const featured = [
  {
    id: "aarrt87tgghjy755",
    imgUrl:
      "https://hotsaucenaija.com/wp-content/uploads/2020/03/Best-Nigerian-Restaurants-in-Atlanta-Georgia.jpg",
    title: "Hot Sauce Naija",
    rating: "4.6",
    genre: "fine dining",
    genreId: "y777yyrfdd12345678",
    address: "BBQ road, B Avenue",
    short_description: "Tasty Local Meals",
    dishes: [],
    long: 45,
    lat: 5,
  },
  {
    id: "aadyu887t66ttr5yu",
    imgUrl:
      "https://www.nairaland.com/attachments/2646937_109786867836256050641171798537151245381301n_jpeg542b2f9978512b9e7515fcd82ab9eb4b",
    title: "La Mango",
    rating: "4.6",
    genre: "fine dining",
    genreId: "y777yyrfdd12345678",
    address: "311 road,cool street",
    short_description: "Enjoy your meal with a beautiful scenery",
    dishes: [],
    long: 45,
    lat: 5,
  },
  {
    id: "aadyu887tgghjuyu",
    imgUrl:
      "https://media-cdn.tripadvisor.com/media/photo-s/1d/45/34/3a/wide-range-of-international.jpg",
    title: "De Bull Restaurant and Bar",
    rating: "4.6",
    genre: "fine dining",
    genreId: "y777yyrfdd12345678",
    address: "BBQ road, A Avenue",
    short_description: "Enjoy meals like never before",
    dishes: [],
    long: 45,
    lat: 5,
  },
  {
    id: "6hy665gr4433rf5",
    imgUrl:
      "https://res.cloudinary.com/hello-world/image/upload/v1551791304/gn1q5yxi4urkp2dohjfu.jpg",
    title: "Ocean Basket",
    rating: "4.3",
    genre: "fine dining",
    genreId: "y777yyrfdd12345678",
    address: "wall street,cole road",
    short_description: "Enjoy sea food with comfort",
    dishes: [],
    long: 45,
    lat: 5,
  },
];

export const restaurants = [
    {
      id: "aadyu887t66ttr5yu",
      imgUrl:
        "https://www.nairaland.com/attachments/2646937_109786867836256050641171798537151245381301n_jpeg542b2f9978512b9e7515fcd82ab9eb4b",
      title: "La Mango",
      rating: "4.6",
      genre: "fine dining",
      genreId: "y777yyrfdd12345678",
      address: "311 road,cool street",
      short_description: "Enjoy your meal with a beautiful scenery",
      dishes: [],
      long: 45,
      lat: 5,
    },
    {
        id: "abcd1234cdbw",
        imgUrl: "https://links.papareact.com/gn7",
        title: "Special Sushi",
        rating: "5",
        genre: "continental",
        genreId: "y777yyrfdd12345",
        address: "wall street,cole road",
        short_description: "healthy meal,for all",
        dishes: [],
        long: 45,
        lat: 5,
      },
      {
        id: "efgh1234cebl",
        imgUrl: "https://www.nandos.com/wp-content/uploads/2022/04/our-food.jpg",
        title: "Nando's",
        rating: "4.5",
        genre: "fast food",
        genreId: "y777yyrfdd1234",
        address: "welsh street,cool drive",
        short_description: "enjoyable fast meal",
        dishes: [],
        long: 45,
        lat: 5,
      },
      {
        id: "aarrt87tgghjy755",
        imgUrl:
          "https://hotsaucenaija.com/wp-content/uploads/2020/03/Best-Nigerian-Restaurants-in-Atlanta-Georgia.jpg",
        title: "Hot Sauce Naija",
        rating: "4.6",
        genre: "fine dining",
        genreId: "y777yyrfdd12345678",
        address: "BBQ road, B Avenue",
        short_description: "Tasty Local Meals",
        dishes: [],
        long: 45,
        lat: 5,
      },
    
      {
        id: "efghrr556777ieb0",
        imgUrl:
          "https://media-cdn.tripadvisor.com/media/photo-s/15/9e/05/d1/grilled-prawn.jpg",
        title: "Turtle Bay",
        rating: "4.9",
        genre: "sea food",
        genreId: "y777yyrfdd123456",
        address: "wall street,cole road",
        short_description: "sea food delight",
        dishes: [],
        long: 45,
        lat: 5,
      },
      {
        id: "yytuivvvgyy78",
        imgUrl:
          "https://hips.hearstapps.com/hmg-prod/images/cold-stone-creamery-halloween-boo-batter-ice-cream-1601567052.jpg",
        title: "Cold Stone Creamery",
        rating: "3.5",
        genre: "ice cream",
        genreId: "y777yyrfdd1234567",
        address: "stone street,cold avenue",
        short_description: "yummy flavours available",
        dishes: [],
        long: 45,
        lat: 5,
      },
      {
        id: "667gttyu6777",
        imgUrl:
          "https://d1ralsognjng37.cloudfront.net/018f79b0-182e-4c4f-a625-8600e582a1e1.jpeg",
        title: "KFC",
        rating: "4.0",
        genre: "fast food",
        genreId: "y777yyrfdd1234",
        address: "Aron's ville,Duncan drive",
        short_description: "Delicious Crispy Chickens",
        dishes: [],
        long: 45,
        lat: 5,
      },
      {
        id: "aadyu887tgghjuyu",
        imgUrl:
          "https://media-cdn.tripadvisor.com/media/photo-s/1d/45/34/3a/wide-range-of-international.jpg",
        title: "De Bull Restaurant and Bar",
        rating: "4.6",
        genre: "fine dining",
        genreId: "y777yyrfdd12345678",
        address: "BBQ road, A Avenue",
        short_description: "Enjoy meals like never before",
        dishes: [],
        long: 45,
        lat: 5,
      },
      {
        id: "6hy665gr4433rf5",
        imgUrl:
          "https://res.cloudinary.com/hello-world/image/upload/v1551791304/gn1q5yxi4urkp2dohjfu.jpg",
        title: "Ocean Basket",
        rating: "4.3",
        genre: "fine dining",
        genreId: "y777yyrfdd12345678",
        address: "wall street,cole road",
        short_description: "Enjoy sea food with comfort",
        dishes: [],
        long: 45,
        lat: 5,
      },
  ];