export const offers = [
  {
    id: "abcd1234cdbw",
    imgUrl: "https://links.papareact.com/gn7",
    title: "Special Sushi",
    rating: "5",
    genre: "continental",
    genreId: "y777yyrfdd12345",
    address: "wall street,cole road",
    short_description: "healthy meal,for all",
    dishes: [{id:"1234esw32",name:"Tuna Sushi Pizza",description:"tempura battered rice crust ,crabsticks ,cream cheese ,tuna tartare ,unagi sauce, soca sauce, sesame seeds, chives ",price:7500,image:"https://www.onthewater.com/wp-content/uploads/2015/11/tuna-pizza-2.jpg"},
        {id:"1234esw33",name:"Chef Special Rainbow Maki",description:"crab ,unagi,mayo,wrap with salmon, tuna, hamachi",price:9500,image:"https://i.pinimg.com/736x/b8/73/1e/b8731e1b4bf311337626045a780c2487--rainbow-roll-maki.jpg"},
        {id:"1234esw34",name:"California Sunshine",description:"crab-ebi sushi-avocado-cucumber-spinach-spicy mayo-sushi rice-nori-ginger-wasabi-tobiko ",price:5650,image:"http://theblowfishgroup.com/izanagi/wp-content/uploads/2018/12/iza10014-2.jpg"}],
    long: 45,
    lat: 5,
  },
  {
    id: "efgh1234cebl",
    imgUrl: "https://www.nandos.com/wp-content/uploads/2022/04/our-food.jpg",
    title: "Nando's",
    rating: "4.5",
    genre: "fast food",
    genreId: "y777yyrfdd1234",
    address: "welsh street,cool drive",
    short_description: "enjoyable fast meal",
    dishes: [{id:"1234esw22",name:"Grilled Chicken Burger",quantity:5,description:"Chicken breast infused with PERi-PERi and grilled to your favourite spice. Served in a Portuguese Roll with Lemon & Herb mayo, lettuce, tomato and PERi-Ketchup",price:4500,image:"https://images.menu.nandos.dev/uk/burgers-pittas-wraps/640x360/butterfly-burger-39.Image-16-9.103227.jpg"},
    {id:"1234esw23",name:"Chicken Butterfly",quantity:3,description:"Two chicken breasts, flame-grilled with crispy skin. Infused with PERi-PERi and served in your choice of spice.",price:8000,image:"https://images.menu.nandos.dev/uk/pe-ri-pe-ri-chicken/640x360/chicken-butterfly-10.Image-16-9.093328.jpg"},
    {id:"1234esw24",name:"Wing Platter",quantity:6,description:"10 Chicken Wings with either 2 large or 4 regular sides. Great for two people.",price:12000,image:"https://images.menu.nandos.dev/uk/sharing-platters/640x360/wing-platter-52.Image-16-9.102140.jpg"},],
    long: 45,
    lat: 5,
  },

  {
    id: "efghrr556777ieb0",
    imgUrl:
      "https://media-cdn.tripadvisor.com/media/photo-s/15/9e/05/d1/grilled-prawn.jpg",
    title: "Turtle Bay",
    rating: "4.9",
    genre: "sea food",
    genreId: "y777yyrfdd123456",
    address: "wall street,cole road",
    short_description: "sea food delight",
    dishes: [{id:"1234esw52",name:"Sweetcorn Fritters",description:"Crunchy on the outside, fluffy on the inside - sweetcorn, onion and chilli, topped with tangy pickled pink onions, fresh mango mole and a kick of hot sauce",price:5000,image:"https://img.taste.com.au/ZwWW92ML/taste/2021/01/crispiest-fritters-ever-168502-2.jpg" },
    {id:"1234esw53",name:"Mac & Cheese Bites",description:"Little balls of macaroni, cooked in a cheddar cheese sauce, crispy fried, topped with sweet chilli mango mole",price:2000,image:"https://www.oldhousetonewhome.net/wp-content/uploads/2015/03/Mini-Macaroni-and-Cheese-Bites4.jpg"},
    {id:"1234esw54",name:"Crispy Chilli Squid",description:"Strips of squid marinated in mildly spiced coconut milk, crumbed and crisped, with mango mole and mild jerk mayo",price:6650,image:"https://www.unileverfoodsolutions.com.au/dam/global-ufs/mcos/ANZ/calcmenu/recipes/AU-recipes/red-meats-&-red-meat-dishes/crispy-squid-with-smoked-chilli-aioli/main-header.jpg"}],
    long: 45,
    lat: 5,
  },
  {
    id: "yytuivvvgyy78",
    imgUrl:
      "https://hips.hearstapps.com/hmg-prod/images/cold-stone-creamery-halloween-boo-batter-ice-cream-1601567052.jpg",
    title: "Cold Stone Creamery",
    rating: "3.5",
    genre: "ice cream",
    genreId: "y777yyrfdd1234567",
    address: "stone street,cold avenue",
    short_description: "yummy flavours available",
    dishes: [{name:"chocolate devotion",description:"choclate icecream with chocolate chip, brownie and fudge",price:3500,image:"https://www.coldstonecreamery.com/assets/img/products/signaturecreations/chocolatedevotion.jpg"},
    {name:"berry berry berry good",description:"sweetcream icecream with blueberry,strawberry and raspberry",price:3900,image:"https://www.coldstonecreamery.com/assets/img/products/signaturecreations/berryberryberrygood.jpg"},
    {name:"coffee lovers only",description:"coffee icecream with caramel,roasted almond and health bar",price:4500,image:"https://www.coldstonecreamery.com/assets/img/products/signaturecreations/coffeloversonly.jpg"}],
    long: 45,
    lat: 5,
  },
  {
    id: "667gttyu6777",
    imgUrl:
      "https://d1ralsognjng37.cloudfront.net/018f79b0-182e-4c4f-a625-8600e582a1e1.jpeg",
    title: "KFC",
    rating: "4.0",
    genre: "fast food",
    genreId: "y777yyrfdd1234",
    address: "Aron's ville,Duncan drive",
    short_description: "Delicious Crispy Chickens",
    dishes: [{name:"21 Pcs KFC Bucket",description:"21 pieces of chicken hot & crispy / Original",price:9800,image:"https://martjackamstorage.azureedge.net/am-resources/4b24cc55-db82-4ab3-84dd-350bbc5e3a93/Images/ProductImages/Source/aColonel.png",},
    {name:"KFC Celebration Feast Bucket",description:"3 pieces of chicken hot & crispy / Original, 6 pieces of wings, 6 pieces of strips",price:13000,image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-PR00000892.jpg?ver=21.38"},
    {name:"Double Zinger Burger",description:"Two Zinger fillets acting as the bun, sandwiching a golden hash brown, a slice of cheese and tomato sauce",price:6000,image:"https://img.taste.com.au/8k9X7AJ6/taste/2021/11/kfc-zinger-crunch-range-174613-1.jpg"}],
    long: 45,
    lat: 5,
  },
  {
    id: "aadyu887tgghjuyu",
    imgUrl:
      "https://media-cdn.tripadvisor.com/media/photo-s/1d/45/34/3a/wide-range-of-international.jpg",
    title: "De Bull Restaurant and Bar",
    rating: "4.6",
    genre: "fine dining",
    genreId: "y777yyrfdd12345678",
    address: "BBQ road, A Avenue",
    short_description: "Enjoy meals like never before",
    dishes: [{name:"Side Salad",description:"tomatoes, onions, cucumbers, green peppers, feta cheese, olives, oregano",price:7000,image:"https://www.garnishandglaze.com/wp-content/uploads/2021/03/easy-side-salad-6.jpg"},
    {name:"Salmon and Avocado Greek Salad",description:"tomato, cucumber, green peppers, onion, feta, salmon, oregano, spring onion",price:12000,image:"https://www.jessicagavin.com/wp-content/uploads/2021/07/greek-salad-3-1200.jpg"},
    {name:"Sweet Prawn",description:"sushi rice, rice vinegar, prawn, rocket, avocado, flour, palm oil, panko crumbs, sweet soy sauce",price:9000,image:"https://therecipecritic.com/wp-content/uploads/2019/02/sweet-and-sour-shrimp-4.jpg"}],
    long: 45,
    lat: 5,
  },
  {
    id: "6hy665gr4433rf5",
    imgUrl:
      "https://res.cloudinary.com/hello-world/image/upload/v1551791304/gn1q5yxi4urkp2dohjfu.jpg",
    title: "Ocean Basket",
    rating: "4.3",
    genre: "fine dining",
    genreId: "y777yyrfdd12345678",
    address: "wall street,cole road",
    short_description: "Enjoy sea food with comfort",
    dishes: [{name:"calamari",description:"calamari, flour, palm oil, creamy lemon sauce, lemon",price:5780,image:"https://www.thespruceeats.com/thmb/xBoL0LGvHA-WGVZSrXNMj0yqmpI=/1332x1332/smart/filters:no_upscale()/fried-calamari-2019531-hero-01-e294f265d7e84c0f89d4b5759759ffbf.jpg"},
    {name:"Seared Salmon Salad",description:"avocado, salmon, cucumber, ponzu sauce, sesame seeds",price:8950,image:"https://images.heb.com/is/image/HEBGrocery/recipe-hm-large/chopped-salad-with-seared-salmon-recipe.jpg"},
    {name:"Famous Fish and Chips",description:"hake, flour, palm oil, chips, creamy lemon, lemon",price:5950,image:"https://nigeria.oceanbasket.com/wp-content/uploads/sites/10/nf_image/fish-and-chips-7c5benzr2tx9bfvqd8w6p9jvw.png"}],
    long: 45,
    lat: 5,
  },
];
export const discount = [
  {
    id: "efgh1234cebl",
    imgUrl: "https://www.nandos.com/wp-content/uploads/2022/04/our-food.jpg",
    title: "Nando's",
    rating: "4.5",
    genre: "fast food",
    genreId: "y777yyrfdd1234",
    address: "welsh street,cool drive",
    short_description: "enjoyable fast meal",
    dishes: [{id:"1234esw22",name:"Grilled Chicken Burger",quantity:5,description:"Chicken breast infused with PERi-PERi and grilled to your favourite spice. Served in a Portuguese Roll with Lemon & Herb mayo, lettuce, tomato and PERi-Ketchup",price:4500,image:"https://images.menu.nandos.dev/uk/burgers-pittas-wraps/640x360/butterfly-burger-39.Image-16-9.103227.jpg"},
    {id:"1234esw23",name:"Chicken Butterfly",quantity:3,description:"Two chicken breasts, flame-grilled with crispy skin. Infused with PERi-PERi and served in your choice of spice.",price:8000,image:"https://images.menu.nandos.dev/uk/pe-ri-pe-ri-chicken/640x360/chicken-butterfly-10.Image-16-9.093328.jpg"},
    {id:"1234esw24",name:"Wing Platter",quantity:6,description:"10 Chicken Wings with either 2 large or 4 regular sides. Great for two people.",price:12000,image:"https://images.menu.nandos.dev/uk/sharing-platters/640x360/wing-platter-52.Image-16-9.102140.jpg"},],
    long: 45,
    lat: 5,
  },

  {
    id: "efghrr556777ieb0",
    imgUrl:
      "https://media-cdn.tripadvisor.com/media/photo-s/15/9e/05/d1/grilled-prawn.jpg",
    title: "Turtle Bay",
    rating: "4.9",
    genre: "sea food",
    genreId: "y777yyrfdd123456",
    address: "wall street,cole road",
    short_description: "sea food delight",
    dishes: [{id:"1234esw52",name:"Sweetcorn Fritters",description:"Crunchy on the outside, fluffy on the inside - sweetcorn, onion and chilli, topped with tangy pickled pink onions, fresh mango mole and a kick of hot sauce",price:5000,image:"https://img.taste.com.au/ZwWW92ML/taste/2021/01/crispiest-fritters-ever-168502-2.jpg" },
    {id:"1234esw53",name:"Mac & Cheese Bites",description:"Little balls of macaroni, cooked in a cheddar cheese sauce, crispy fried, topped with sweet chilli mango mole",price:2000,image:"https://www.oldhousetonewhome.net/wp-content/uploads/2015/03/Mini-Macaroni-and-Cheese-Bites4.jpg"},
    {id:"1234esw54",name:"Crispy Chilli Squid",description:"Strips of squid marinated in mildly spiced coconut milk, crumbed and crisped, with mango mole and mild jerk mayo",price:6650,image:"https://www.unileverfoodsolutions.com.au/dam/global-ufs/mcos/ANZ/calcmenu/recipes/AU-recipes/red-meats-&-red-meat-dishes/crispy-squid-with-smoked-chilli-aioli/main-header.jpg"}],
    long: 45,
    lat: 5,
  },
  {
    id: "yytuivvvgyy78",
    imgUrl:
      "https://hips.hearstapps.com/hmg-prod/images/cold-stone-creamery-halloween-boo-batter-ice-cream-1601567052.jpg",
    title: "Cold Stone Creamery",
    rating: "3.5",
    genre: "fast food",
    genreId: "y777yyrfdd1234",
    address: "stone street,cold avenue",
    short_description: "yummy flavours available",
    dishes: [{name:"chocolate devotion",description:"choclate icecream with chocolate chip, brownie and fudge",price:3500,image:"https://www.coldstonecreamery.com/assets/img/products/signaturecreations/chocolatedevotion.jpg"},
    {name:"berry berry berry good",description:"sweetcream icecream with blueberry,strawberry and raspberry",price:3900,image:"https://www.coldstonecreamery.com/assets/img/products/signaturecreations/berryberryberrygood.jpg"},
    {name:"coffee lovers only",description:"coffee icecream with caramel,roasted almond and health bar",price:4500,image:"https://www.coldstonecreamery.com/assets/img/products/signaturecreations/coffeloversonly.jpg"}],
    long: 45,
    lat: 5,
  },
  {
    id: "667gttyu6777",
    imgUrl:
      "https://d1ralsognjng37.cloudfront.net/018f79b0-182e-4c4f-a625-8600e582a1e1.jpeg",
    title: "KFC",
    rating: "4.0",
    genre: "fast food",
    genreId: "y777yyrfdd1234",
    address: "Aron's ville,Duncan drive",
    short_description: "Delicious Crispy Chickens",
    dishes: [{name:"21 Pcs KFC Bucket",description:"21 pieces of chicken hot & crispy / Original",price:9800,image:"https://martjackamstorage.azureedge.net/am-resources/4b24cc55-db82-4ab3-84dd-350bbc5e3a93/Images/ProductImages/Source/aColonel.png",},
    {name:"KFC Celebration Feast Bucket",description:"3 pieces of chicken hot & crispy / Original, 6 pieces of wings, 6 pieces of strips",price:13000,image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-PR00000892.jpg?ver=21.38"},
    {name:"Double Zinger Burger",description:"Two Zinger fillets acting as the bun, sandwiching a golden hash brown, a slice of cheese and tomato sauce",price:6000,image:"https://img.taste.com.au/8k9X7AJ6/taste/2021/11/kfc-zinger-crunch-range-174613-1.jpg"}],
    long: 45,
    lat: 5,
  },
];

export const featured = [
  {
    id: "aarrt87tgghjy755",
    imgUrl:
      "https://hotsaucenaija.com/wp-content/uploads/2020/03/Best-Nigerian-Restaurants-in-Atlanta-Georgia.jpg",
    title: "Hot Sauce Naija",
    rating: "4.6",
    genre: "fine dining",
    genreId: "y777yyrfdd12345678",
    address: "BBQ road, B Avenue",
    short_description: "Tasty Local Meals",
    dishes: [{id:"1234esw42",name:"FisherMan Soup",description:"Fisherman soup is a simple soup made with fish and other seafood as its protein source",price:7000,image:"https://scm-assets.constant.co/scm/unilever/e9dc924f238fa6cc29465942875fe8f0/2ce7e5b9-ba1f-4462-b379-2a65792288c2.jpg"},
    {id:"1234esw43",name:"EGUSI SOUP",description:"This is a flavorful dish of cubed beef and shrimp cooked with spinach and ground seeds in a spicy tomato base.",price:4000,image:"https://www.pointoneafricancuisine.com/wp-content/uploads/2021/05/Egusi.jpeg"},
    {id:"1234esw44",name:"Abak Soup",description:"this s a palm nut juice-based soup",price:4000,image:"https://guardian.ng/wp-content/uploads/2019/07/Atama-soup.-Photo-Excellent-Nigerian-recipes-e1562458145235.jpg"}],
    long: 45,
    lat: 5,
  },
  {
    id: "aadyu887t66ttr5yu",
    imgUrl:
      "https://www.nairaland.com/attachments/2646937_109786867836256050641171798537151245381301n_jpeg542b2f9978512b9e7515fcd82ab9eb4b",
    title: "La Mango",
    rating: "4.6",
    genre: "fine dining",
    genreId: "y777yyrfdd12345678",
    address: "311 road,cool street",
    short_description: "Enjoy your meal with a beautiful scenery",
    dishes: [{id:"1234esw12",name:"CROAKER A LA MACEDOUNE",description:"delicious meal made to your taste",price:10000, image:"https://lh3.googleusercontent.com/p/AF1QipOCdFHixdy8Ewn9Vf5DL5HRPUQoec6xh_-NXbs" },
    {id:"1234esw13",name:"CHICKEN CAESAR SALAD",description:"enjoy our salad, leaving you wanting more",price:3500,image:"https://www.spendwithpennies.com/wp-content/uploads/2021/04/FT-Chicken-Caesar-Salad-SpendWithPennies-4.jpg"},
    {id:"1234esw14",name:"PRAWNS FAJITA",description:"enjoy prawns with our special sauce",price:4500,image:"https://www.acouplecooks.com/wp-content/uploads/2021/03/Shrimp-Fajitas-007.jpg"}],
    long: 45,
    lat: 5,
  },
  {
    id: "aadyu887tgghjuyu",
    imgUrl:
      "https://media-cdn.tripadvisor.com/media/photo-s/1d/45/34/3a/wide-range-of-international.jpg",
    title: "De Bull Restaurant and Bar",
    rating: "4.6",
    genre: "fine dining",
    genreId: "y777yyrfdd12345678",
    address: "BBQ road, A Avenue",
    short_description: "Enjoy meals like never before",
    dishes: [{name:"Side Salad",description:"tomatoes, onions, cucumbers, green peppers, feta cheese, olives, oregano",price:7000,image:"https://www.garnishandglaze.com/wp-content/uploads/2021/03/easy-side-salad-6.jpg"},
    {name:"Salmon and Avocado Greek Salad",description:"tomato, cucumber, green peppers, onion, feta, salmon, oregano, spring onion",price:12000,image:"https://www.jessicagavin.com/wp-content/uploads/2021/07/greek-salad-3-1200.jpg"},
    {name:"Sweet Prawn",description:"sushi rice, rice vinegar, prawn, rocket, avocado, flour, palm oil, panko crumbs, sweet soy sauce",price:9000,image:"https://therecipecritic.com/wp-content/uploads/2019/02/sweet-and-sour-shrimp-4.jpg"}],
    long: 45,
    lat: 5,
  },
  {
    id: "6hy665gr4433rf5",
    imgUrl:
      "https://res.cloudinary.com/hello-world/image/upload/v1551791304/gn1q5yxi4urkp2dohjfu.jpg",
    title: "Ocean Basket",
    rating: "4.3",
    genre: "fine dining",
    genreId: "y777yyrfdd12345678",
    address: "wall street,cole road",
    short_description: "Enjoy sea food with comfort",
    dishes: [{name:"calamari",description:"calamari, flour, palm oil, creamy lemon sauce, lemon",price:5780,image:"https://www.thespruceeats.com/thmb/xBoL0LGvHA-WGVZSrXNMj0yqmpI=/1332x1332/smart/filters:no_upscale()/fried-calamari-2019531-hero-01-e294f265d7e84c0f89d4b5759759ffbf.jpg"},
    {name:"Seared Salmon Salad",description:"avocado, salmon, cucumber, ponzu sauce, sesame seeds",price:8950,image:"https://images.heb.com/is/image/HEBGrocery/recipe-hm-large/chopped-salad-with-seared-salmon-recipe.jpg"},
    {name:"Famous Fish and Chips",description:"hake, flour, palm oil, chips, creamy lemon, lemon",price:5950,image:"https://nigeria.oceanbasket.com/wp-content/uploads/sites/10/nf_image/fish-and-chips-7c5benzr2tx9bfvqd8w6p9jvw.png"}],
    long: 45,
    lat: 5,
  },
];

export const restaurants = [
    {
      id: "aadyu887t66ttr5yu",
      imgUrl:
        "https://www.nairaland.com/attachments/2646937_109786867836256050641171798537151245381301n_jpeg542b2f9978512b9e7515fcd82ab9eb4b",
      title: "La Mango",
      rating: "4.6",
      genre: "fine dining",
      genreId: "y777yyrfdd12345678",
      address: "311 road,cool street",
      short_description: "Enjoy your meal with a beautiful scenery",
      dishes: [{id:"1234esw12",name:"CROAKER A LA MACEDOUNE",description:"delicious meal made to your taste",price:10000, image:"https://lh3.googleusercontent.com/p/AF1QipOCdFHixdy8Ewn9Vf5DL5HRPUQoec6xh_-NXbs" },
      {id:"1234esw13",name:"CHICKEN CAESAR SALAD",description:"enjoy our salad, leaving you wanting more",price:3500,image:"https://www.spendwithpennies.com/wp-content/uploads/2021/04/FT-Chicken-Caesar-Salad-SpendWithPennies-4.jpg"},
      {id:"1234esw14",name:"PRAWNS FAJITA",description:"enjoy prawns with our special sauce",price:4500,image:"https://www.acouplecooks.com/wp-content/uploads/2021/03/Shrimp-Fajitas-007.jpg"}],
      long: 45,
      lat: 5,
    },
    {
        id: "abcd1234cdbw",
        imgUrl: "https://links.papareact.com/gn7",
        title: "Special Sushi",
        rating: "5",
        genre: "continental",
        genreId: "y777yyrfdd12345",
        address: "wall street,cole road",
        short_description: "healthy meal,for all",
        dishes: [{id:"1234esw32",name:"Tuna Sushi Pizza",description:"tempura battered rice crust ,crabsticks ,cream cheese ,tuna tartare ,unagi sauce, soca sauce, sesame seeds, chives ",price:7500,image:"https://www.onthewater.com/wp-content/uploads/2015/11/tuna-pizza-2.jpg"},
        {id:"1234esw33",name:"Chef Special Rainbow Maki",description:"crab ,unagi,mayo,wrap with salmon, tuna, hamachi",price:9500,image:"https://i.pinimg.com/736x/b8/73/1e/b8731e1b4bf311337626045a780c2487--rainbow-roll-maki.jpg"},
        {id:"1234esw34",name:"California Sunshine",description:"crab-ebi sushi-avocado-cucumber-spinach-spicy mayo-sushi rice-nori-ginger-wasabi-tobiko ",price:5650,image:"http://theblowfishgroup.com/izanagi/wp-content/uploads/2018/12/iza10014-2.jpg"}],
        long: 45,
        lat: 5,
      },
      {
        id: "efgh1234cebl",
        imgUrl: "https://www.nandos.com/wp-content/uploads/2022/04/our-food.jpg",
        title: "Nando's",
        rating: "4.5",
        genre: "fast food",
        genreId: "y777yyrfdd1234",
        address: "welsh street,cool drive",
        short_description: "enjoyable fast meal",
        dishes: [{id:"1234esw22",name:"Grilled Chicken Burger",quantity:5,description:"Chicken breast infused with PERi-PERi and grilled to your favourite spice. Served in a Portuguese Roll with Lemon & Herb mayo, lettuce, tomato and PERi-Ketchup",price:4500,image:"https://images.menu.nandos.dev/uk/burgers-pittas-wraps/640x360/butterfly-burger-39.Image-16-9.103227.jpg"},
        {id:"1234esw23",name:"Chicken Butterfly",quantity:3,description:"Two chicken breasts, flame-grilled with crispy skin. Infused with PERi-PERi and served in your choice of spice.",price:8000,image:"https://images.menu.nandos.dev/uk/pe-ri-pe-ri-chicken/640x360/chicken-butterfly-10.Image-16-9.093328.jpg"},
        {id:"1234esw24",name:"Wing Platter",quantity:6,description:"10 Chicken Wings with either 2 large or 4 regular sides. Great for two people.",price:12000,image:"https://images.menu.nandos.dev/uk/sharing-platters/640x360/wing-platter-52.Image-16-9.102140.jpg"},],
        long: 45,
        lat: 5,
      },
      {
        id: "aarrt87tgghjy755",
        imgUrl:
          "https://hotsaucenaija.com/wp-content/uploads/2020/03/Best-Nigerian-Restaurants-in-Atlanta-Georgia.jpg",
        title: "Hot Sauce Naija",
        rating: "4.6",
        genre: "fine dining",
        genreId: "y777yyrfdd12345678",
        address: "BBQ road, B Avenue",
        short_description: "Tasty Local Meals",
        dishes: [{id:"1234esw42",name:"FisherMan Soup",description:"Fisherman soup is a simple soup made with fish and other seafood as its protein source",price:7000,image:"https://scm-assets.constant.co/scm/unilever/e9dc924f238fa6cc29465942875fe8f0/2ce7e5b9-ba1f-4462-b379-2a65792288c2.jpg"},
        {id:"1234esw43",name:"EGUSI SOUP",description:"This is a flavorful dish of cubed beef and shrimp cooked with spinach and ground seeds in a spicy tomato base.",price:4000,image:"https://www.pointoneafricancuisine.com/wp-content/uploads/2021/05/Egusi.jpeg"},
        {id:"1234esw44",name:"Abak Soup",description:"this s a palm nut juice-based soup",price:4000,image:"https://guardian.ng/wp-content/uploads/2019/07/Atama-soup.-Photo-Excellent-Nigerian-recipes-e1562458145235.jpg"}],
        long: 45,
        lat: 5,
      },
    
      {
        id: "efghrr556777ieb0",
        imgUrl:
          "https://media-cdn.tripadvisor.com/media/photo-s/15/9e/05/d1/grilled-prawn.jpg",
        title: "Turtle Bay",
        rating: "4.9",
        genre: "sea food",
        genreId: "y777yyrfdd123456",
        address: "wall street,cole road",
        short_description: "sea food delight",
        dishes: [{id:"1234esw42",name:"Sweetcorn Fritters",description:"Crunchy on the outside, fluffy on the inside - sweetcorn, onion and chilli, topped with tangy pickled pink onions, fresh mango mole and a kick of hot sauce",price:5000,image:"https://img.taste.com.au/ZwWW92ML/taste/2021/01/crispiest-fritters-ever-168502-2.jpg" },
        {id:"1234esw53",name:"Mac & Cheese Bites",description:"Little balls of macaroni, cooked in a cheddar cheese sauce, crispy fried, topped with sweet chilli mango mole",price:2000,image:"https://www.oldhousetonewhome.net/wp-content/uploads/2015/03/Mini-Macaroni-and-Cheese-Bites4.jpg"},
        {id:"1234esw54",name:"Crispy Chilli Squid",description:"Strips of squid marinated in mildly spiced coconut milk, crumbed and crisped, with mango mole and mild jerk mayo",price:6650,image:"https://www.unileverfoodsolutions.com.au/dam/global-ufs/mcos/ANZ/calcmenu/recipes/AU-recipes/red-meats-&-red-meat-dishes/crispy-squid-with-smoked-chilli-aioli/main-header.jpg"}],
        long: 45,
        lat: 5,
      },
      {
        id: "yytuivvvgyy78",
        imgUrl:
          "https://hips.hearstapps.com/hmg-prod/images/cold-stone-creamery-halloween-boo-batter-ice-cream-1601567052.jpg",
        title: "Cold Stone Creamery",
        rating: "3.5",
        genre: "ice cream",
        genreId: "y777yyrfdd1234567",
        address: "stone street,cold avenue",
        short_description: "yummy flavours available",
        dishes: [{name:"chocolate devotion",description:"choclate icecream with chocolate chip, brownie and fudge",price:3500,image:"https://www.coldstonecreamery.com/assets/img/products/signaturecreations/chocolatedevotion.jpg"},
        {name:"berry berry berry good",description:"sweetcream icecream with blueberry,strawberry and raspberry",price:3900,image:"https://www.coldstonecreamery.com/assets/img/products/signaturecreations/berryberryberrygood.jpg"},
        {name:"coffee lovers only",description:"coffee icecream with caramel,roasted almond and health bar",price:4500,image:"https://www.coldstonecreamery.com/assets/img/products/signaturecreations/coffeloversonly.jpg"}],
        long: 45,
        lat: 5,
      },
      {
        id: "667gttyu6777",
        imgUrl:
          "https://d1ralsognjng37.cloudfront.net/018f79b0-182e-4c4f-a625-8600e582a1e1.jpeg",
        title: "KFC",
        rating: "4.0",
        genre: "fast food",
        genreId: "y777yyrfdd1234",
        address: "Aron's ville,Duncan drive",
        short_description: "Delicious Crispy Chickens",
        dishes: [{name:"21 Pcs KFC Bucket",description:"21 pieces of chicken hot & crispy / Original",price:9800,image:"https://martjackamstorage.azureedge.net/am-resources/4b24cc55-db82-4ab3-84dd-350bbc5e3a93/Images/ProductImages/Source/aColonel.png",},
        {name:"KFC Celebration Feast Bucket",description:"3 pieces of chicken hot & crispy / Original, 6 pieces of wings, 6 pieces of strips",price:13000,image:"https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-PR00000892.jpg?ver=21.38"},
        {name:"Double Zinger Burger",description:"Two Zinger fillets acting as the bun, sandwiching a golden hash brown, a slice of cheese and tomato sauce",price:6000,image:"https://img.taste.com.au/8k9X7AJ6/taste/2021/11/kfc-zinger-crunch-range-174613-1.jpg"}],
        long: 45,
        lat: 5,
      },
      {
        id: "aadyu887tgghjuyu",
        imgUrl:
          "https://media-cdn.tripadvisor.com/media/photo-s/1d/45/34/3a/wide-range-of-international.jpg",
        title: "De Bull Restaurant and Bar",
        rating: "4.6",
        genre: "fine dining",
        genreId: "y777yyrfdd12345678",
        address: "BBQ road, A Avenue",
        short_description: "Enjoy meals like never before",
        dishes: [{name:"Side Salad",description:"tomatoes, onions, cucumbers, green peppers, feta cheese, olives, oregano",price:7000,image:"https://www.garnishandglaze.com/wp-content/uploads/2021/03/easy-side-salad-6.jpg"},
        {name:"Salmon and Avocado Greek Salad",description:"tomato, cucumber, green peppers, onion, feta, salmon, oregano, spring onion",price:12000,image:"https://www.jessicagavin.com/wp-content/uploads/2021/07/greek-salad-3-1200.jpg"},
        {name:"Sweet Prawn",description:"sushi rice, rice vinegar, prawn, rocket, avocado, flour, palm oil, panko crumbs, sweet soy sauce",price:9000,image:"https://therecipecritic.com/wp-content/uploads/2019/02/sweet-and-sour-shrimp-4.jpg"}],
        long: 45,
        lat: 5,
      },
      {
        id: "6hy665gr4433rf5",
        imgUrl:
          "https://res.cloudinary.com/hello-world/image/upload/v1551791304/gn1q5yxi4urkp2dohjfu.jpg",
        title: "Ocean Basket",
        rating: "4.3",
        genre: "fine dining",
        genreId: "y777yyrfdd12345678",
        address: "wall street,cole road",
        short_description: "Enjoy sea food with comfort",
        dishes: [{name:"calamari",description:"calamari, flour, palm oil, creamy lemon sauce, lemon",price:5780,image:"https://www.thespruceeats.com/thmb/xBoL0LGvHA-WGVZSrXNMj0yqmpI=/1332x1332/smart/filters:no_upscale()/fried-calamari-2019531-hero-01-e294f265d7e84c0f89d4b5759759ffbf.jpg"},
        {name:"Seared Salmon Salad",description:"avocado, salmon, cucumber, ponzu sauce, sesame seeds",price:8950,image:"https://images.heb.com/is/image/HEBGrocery/recipe-hm-large/chopped-salad-with-seared-salmon-recipe.jpg"},
        {name:"Famous Fish and Chips",description:"hake, flour, palm oil, chips, creamy lemon, lemon",price:5950,image:"https://nigeria.oceanbasket.com/wp-content/uploads/sites/10/nf_image/fish-and-chips-7c5benzr2tx9bfvqd8w6p9jvw.png"}],
        long: 45,
        lat: 5,
      },
  ];